import React from 'react';

function Preview() {
  // Hard-coded HTML content
  const htmlContent = `
  <div>
    <div style="border-bottom:0.75pt solid #000000; clear:both;">
        <p style="margin-top:0pt; margin-bottom:0pt; widows:0; orphans:0; font-size:24pt;"><strong><span style="font-family:Garamond;">Shannon Chaulet</span></strong></p>
        <p style="margin-top:0pt; margin-bottom:0pt; widows:0; orphans:0; padding-bottom:1pt; font-size:16pt;"><span style="font-family:Garamond;">shannon.chaulet@gmail.com&nbsp;</span><span style="font-family:'Noto Sans Symbols';">❖</span><span style="font-family:Garamond;">&nbsp;(781) 315-2502&nbsp;</span><span style="font-family:'Noto Sans Symbols';">❖</span><span style="font-family:Garamond;">&nbsp;Boston, MA</span></p>
    </div>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; border-bottom:0.75pt solid #000000; padding-bottom:1pt;"><strong><span style="font-family:Garamond;">WORK EXPERIENCE&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:6pt;"><strong><span style="font-family:Garamond;">&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">SprintFWD</span></strong><strong><span style="width:13.87pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:6pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;</span></strong><strong><span style="width:27pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp;&nbsp;</span></strong><strong><span style="font-family:Garamond;">Nov. 2022 &ndash; Present</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">Technical Project Manager</span></em><em><span style="width:2.37pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp;</span></em><em><span style="font-family:Garamond;">Hermosa Beach, CA</span></em></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Led the launch of XPASS 2.0, a premium fitness subscription platform that drove adoption among 3,500+ boutique fitness studios worldwide.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Implemented a product roadmap for Xponential+, an award-winning digital fitness VOD platform.</span></p>
    <p style="margin-top:0pt; margin-left:54pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Courier New';">o</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Resulted in a 15% increase in user engagement and a 10% improvement in retention.</span></p>
    <p style="margin-top:0pt; margin-left:54pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Courier New'; font-size:13pt;">o</span><span style="width:10.2pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Named one of the top Health and Fitness apps of 2023 by www.health.com.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Collaborated with senior leadership to define project objectives, scope, and deliverables, aligning them with the clients strategic goals, resulting in successful product launches and adoption by the user base.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols'; font-size:10pt;">▪</span><span style="width:12pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-family:Garamond;">Oversaw a portfolio of numerous projects with varying requirements and fast feedback loops, meeting deadlines and deliverables on budget and to a high standard of quality.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><strong><span style="font-family:Garamond;">&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">Cambridge Innovation Center</span></strong><strong><span style="width:27.73pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">June 2018 &ndash; Oct. 2022</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">Capital Projects Manager</span></em><em><span style="width:5.75pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></em><em><span style="width:9pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp;</span></em><em><span style="width:21pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp;Cambridge, MA</span></em></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Developed annual capital projects budget with corresponding project priorities at each CIC location across a global campus serving 3,000+ clients.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Leveraged QuickBase data analytics to identify bottlenecks in the project request pipeline, leading to process improvements that reduced request backlogs by 25%.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Employed agile methodologies to enhance product development processes, resulting in faster project delivery and improved customer satisfaction.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">ExploreNow</span></strong><strong><span style="width:6.87pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:24pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp;Jan. 2017 &ndash; May 2018</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">Co-Founder</span></em><em><span style="width:23.75pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp;</span></em><em><span style="width:21pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp;&nbsp;</span></em><em><span style="font-family:Garamond;">Boston, MA</span></em></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Managed the development of an interactive live-streaming service, connecting hosts and clients globally.</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Facilitated product scoping meetings and technical documentation.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">DivcoWest&nbsp;</span></strong><strong><span style="width:13.75pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp;</span></strong><strong><span style="width:21pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:24pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:24pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">May 2015 &ndash; Dec. 2016</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">Services Coordinator</span></em><em><span style="width:26.63pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp;</span></em><em><span style="width:33pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></em><em><span style="width:3pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp;Cambridge, MA&nbsp;</span></em></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Implemented streamlined processes for building maintenance, security, and cleaning services, resulting in increased efficiency, cost-effectiveness, and improved overall tenant experience.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">Finishing Touch Painting</span></strong><strong><span style="width:12.36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp;</span></strong><strong><span style="width:33pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:24pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">Aug. 2011 &ndash;Sept. 2014</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">Owner / Managing Director</span></em><em><span style="width:29.13pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp;</span></em><em><span style="width:33pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></em><em><span style="font-family:Garamond;">Lexington, MA&nbsp;</span></em></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-family:Garamond;">Successfully managed over twenty projects from lead to close-out, generating revenue exceeding $35,000 annually.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; border-bottom:0.75pt solid #000000; padding-bottom:1pt;"><strong><span style="font-family:Garamond;">EDUCATION&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:6pt;"><strong><span style="width:83pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><strong><span style="font-family:Garamond;">University of Massachusetts, Amherst&nbsp;</span></strong><strong><span style="width:21.26pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></strong><strong><span style="width:9pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></strong><strong><span style="width:12pt; font-family:Garamond; display:inline-block;">&nbsp;</span></strong><strong><span style="font-family:Garamond;">&nbsp; &nbsp; &nbsp; &nbsp;</span></strong><strong><span style="font-family:Garamond;">May, 2015&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0;"><em><span style="font-family:Garamond;">BS, Building &amp; Construction Technology</span></em><em><span style="width:14.5pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp;</span></em><em><span style="width:27pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="width:36pt; font-family:Garamond; display:inline-block;">&nbsp;</span></em><em><span style="font-family:Garamond;">&nbsp; &nbsp;&nbsp;</span></em><em><span style="font-family:Garamond;">Amherst, MA</span></em></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; border-bottom:0.75pt solid #000000; padding-bottom:1pt;"><strong><span style="font-family:Garamond;">CERTIFICATIONS, SKILLS &amp; INTERESTS</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; line-height:105%; widows:0; orphans:0; font-size:6pt;"><span style="font-family:Garamond;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0.15pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><strong><span style="font-family:Garamond;">Certifications:&nbsp;</span></strong><span style="font-family:Garamond;">Massachusetts Real Estate License, OSHA-10</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0.15pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><strong><span style="font-family:Garamond;">Skills:&nbsp;</span></strong><span style="line-height:105%; font-family:Garamond; font-size:11pt;">Jira, Figma, HubSpot, Confluence, Software Development, GitHub, Scrum, Agile Methodologies, Technical Documentation, Quality Assurance, Scope Management, Budgeting, Recruiting, Javascript, Python, HTML &amp; CSS</span></p>
    <p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; line-height:105%; widows:0; orphans:0;"><span style="font-family:'Noto Sans Symbols';">▪</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp; &nbsp; &nbsp; &nbsp;</span><strong><span style="font-family:Garamond;">Interests:</span></strong><span style="font-family:Garamond;">&nbsp;Dog Training, Guitar, Piano, International Travel, Running, Reading, DIY Projects, Programming</span></p>
</div>
<p style="bottom: 10px; right: 10px; position: absolute;"><br></p>
  `;

  return (
    <div dangerouslySetInnerHTML={{ __html: htmlContent }}></div>
  );
}

export default Preview;